#!/usr/bin/env Rscript

library(plumber)
library(textcat)
library(jsonlite)
library(urltools)
library(huxtable)
library(magrittr)
library(kableExtra)
library(readr)
#library (rio)
#library (dplyr)
#library (dbplyr)
#library (datos)
#library (tidyverse)
#library (tidyr)
#library(mice)
#library(na.tools)
#library(tidyimpute)
#library(imputeTS)
#library(forecast)

pr <- plumb('api.R')
pr$run(host="0.0.0.0", port=8888)
